//PRINCIPIOS IMPORTANTES
	//1. ABSTRAÇÃO; - Pegar um objeto do mundo real, e "inseri-lo" dentro de seu sistema. 
	//2. ENCAPSULAMENTO - Ter os detalhes de impplementação escondido, e mostrar para quem 
	//precisa usar aquele sistema, mostrar uma interface simples; 
	//3. HERANÇA - Relação "é/um", de forma de re-usar um código! 
	//4. POLIMORFISMO - Um objeto que possui diversas formas. Ou seja, a partir de um conceito generico-para ser mais especifico.
	
