// CÓDIGO NÃO EXECUTAVEL

// Procedural - GOTO - PROGRAMAÇÃO NÃO ESTRUTURADA; 
// Após isso, surge as linguagens estruturadas, gerando
//paradigma procidural. 

//ex procidural, antes você tinha um foco em funções 
//que manipulavam dados. 
procedimento(valor1, valor2, valor3)

// 00 Foca em utilizar dados, e dentro destes dados você
//tem funções

objeto = {
	valor1, valor2, valor3,
		procedimento(){
     //....
     }
}

objeto.processamento() //Foco passou a ser os objetos

//em OO, o objeto tem valores/atributos que tem funções
//dentro deste mesmo objeto. 
//o objeto agrupa comportamento e atributos. 

//PRINCIPIOS IMPORTANTES
	//1. ABSTRAÇÃO; - Pegar um objeto do mundo real, e "inseri-lo" dentro de seu sistema. 
	//2. ENCAPSULAMENTO - Ter os detalhes de impplementação escondido, e mostrar para quem 
	//precisa usar aquele sistema, mostrar uma interface simples; 
	//3. HERANÇA - Relação "é/um", de forma de re-usar um código! 
	//4. POLIMORFISMO - Um objeto que possui diversas formas. Ou seja, a partir de um conceito generico-para ser mais especifico.
	
